### ISSUE TITLE
Table name prefix support for spring data dynamodb

### ISSUE THREAD

**Issue by ravichauhan03** [spring-data-dynamodb/spring-data-dynamodb#144]
## Expected Behavior
Not Supported

## Actual Behavior
We are using spring data dynamodb dependency in our project and initial development was fast. But, not we wanted to have different table prefixes for different environments like dev, stag, prod etc. Can you please support this feature?

## Steps to Reproduce the Problem
I think it is more from the feature development.

## Specifications
  
  - Spring Data DynamoDB Version: 
  - Spring Data Version:
  - AWS SDK Version:
  - Java Version: 
  - Platform Details: 

All those information are logged by `org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory` on `INFO` level on startup.
Or use `java -version` and `mvn dependency:tree | grep -E 'spring|aws'` to provide those version numbers.

**Comment by derjust** [comment]
Hi!
Have you tried the wiki article [Alter table name during runtime](https://github.com/spring-data-dynamodb/spring-data-dynamodb/wiki/Alter-table-name-during-runtime)?

Are you missing any feature?

**Comment by ravichauhan03** [comment]
@derjust : I know to use that feature in AWS SDK. I wanted to use that feature for spring-data. AS of now, when I am using the simpleDynamoDBCrudRepository save method, I am unable to plug the dynamoDBMapperConfig with Table name override as it is not exposed. Can you please help me with that ?

**Comment by derjust** [comment]
How does your `@Configuration` class look like with the `@EnableDynamoDBRepositories(basePackages = "....")` annotation?

**Comment by ravichauhan03** [comment]
Yes, Sebastian. It looks like that. Below is the code snippet:

@Configuration
@EnableDynamoDBRepositories(basePackages =
"com.platform.integration.dynamodb.repository")
public class DynamoDBConfiguration {

    @Autowired
    private AWSDynamoProperties awsDynamoProperties;

    @Autowired
    private Environment environment;

    private static final String TEST_PROFILE="test";

    @Bean
    public AmazonDynamoDB amazonDynamoDB() {
        if(ArrayUtils.isNotEmpty(environment.getActiveProfiles())){
            if(Arrays.stream(environment.getActiveProfiles()).parallel().anyMatch(TEST_PROFILE::contains)){
                return amazonDynamoDBTestInstance();
            }
        }
        AmazonDynamoDBClientBuilder clientBuilder =
AmazonDynamoDBClientBuilder.standard().withRegion(Regions.fromName(awsDynamoProperties.getRegion()));
        if(!StringUtils.isNullOrEmpty(awsDynamoProperties.getAccesskey())){
            clientBuilder  = clientBuilder.withCredentials(new
AWSCredentialsProvider() {

                @Override
                public void refresh() {

                   //DO NOTHING

                }

                @Override
                public AWSCredentials getCredentials() {
                    return amazonAWSCredentials();
                }
            });
        }
        return clientBuilder.build();
    }

    private AmazonDynamoDB amazonDynamoDBTestInstance() {
        AmazonDynamoDB aws = new AmazonDynamoDBClient(amazonAWSCredentials());
        aws.setEndpoint(String.format(awsDynamoProperties.getLocalEndpoint()));
        return aws;
    }

    @Bean
    public AWSCredentials amazonAWSCredentials() {
        return new BasicAWSCredentials(
                awsDynamoProperties.getAccesskey(),
awsDynamoProperties.getSecretkey());
    }

    @Bean
    public DynamoDBMapperConfig dynamoDBMapperConfig() {
        DynamoDBMapperConfig.Builder builder = new
DynamoDBMapperConfig.Builder();
        builder.setTableNameOverride(tableNameOverrider());
        return builder.build();
    }


    private DynamoDBMapperConfig.TableNameOverride tableNameOverrider() {
        String prefix = null;
        if(ArrayUtils.isNotEmpty(environment.getActiveProfiles())){
            for(String profile : environment.getActiveProfiles()){
                if(profile.contains("stag")){
                    prefix="stag_";
                }else if(profile.contains("perf") || profile.contains("perf")){
                    prefix="perf_";
                }else if(profile.contains("dev")){
                    prefix="dev_";
                }
            }
        }
        if(!StringUtils.isNullOrEmpty(prefix)){
            return
DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix(prefix);
        }
        return DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix("");
    }
}



--
Regards,
Ravi Chauhan
+91-9958597300
Skype: ravichauhan03 <ravichauhan03@gmail.com>

**Comment by derjust** [comment]
```java
@Configuration
@EnableDynamoDBRepositories(basePackages =
"com.platform.integration.dynamodb.repository")
public class DynamoDBConfiguration {

    @Autowired
    private AWSDynamoProperties awsDynamoProperties;

    @Autowired
    private Environment environment;

    private static final String TEST_PROFILE="test";

    @Bean
    public AmazonDynamoDB amazonDynamoDB() {
        if(ArrayUtils.isNotEmpty(environment.getActiveProfiles())){
            if(Arrays.stream(environment.getActiveProfiles()).parallel().anyMatch(TEST_PROFILE::contains)){
                return amazonDynamoDBTestInstance();
            }
        }
        AmazonDynamoDBClientBuilder clientBuilder =
AmazonDynamoDBClientBuilder.standard().withRegion(Regions.fromName(awsDynamoProperties.getRegion()));
        if(!StringUtils.isNullOrEmpty(awsDynamoProperties.getAccesskey())){
            clientBuilder  = clientBuilder.withCredentials(new
AWSCredentialsProvider() {

                @Override
                public void refresh() {

                   //DO NOTHING

                }

                @Override
                public AWSCredentials getCredentials() {
                    return amazonAWSCredentials();
                }
            });
        }
        return clientBuilder.build();
    }

    private AmazonDynamoDB amazonDynamoDBTestInstance() {
        AmazonDynamoDB aws = new AmazonDynamoDBClient(amazonAWSCredentials());
        aws.setEndpoint(String.format(awsDynamoProperties.getLocalEndpoint()));
        return aws;
    }

    @Bean
    public AWSCredentials amazonAWSCredentials() {
        return new BasicAWSCredentials(
                awsDynamoProperties.getAccesskey(),
awsDynamoProperties.getSecretkey());
    }

    @Bean
    public DynamoDBMapperConfig dynamoDBMapperConfig() {
        DynamoDBMapperConfig.Builder builder = new
DynamoDBMapperConfig.Builder();
        builder.setTableNameOverride(tableNameOverrider());
        return builder.build();
    }


    private DynamoDBMapperConfig.TableNameOverride tableNameOverrider() {
        String prefix = null;
        if(ArrayUtils.isNotEmpty(environment.getActiveProfiles())){
            for(String profile : environment.getActiveProfiles()){
                if(profile.contains("stag")){
                    prefix="stag_";
                }else if(profile.contains("perf") || profile.contains("perf")){
                    prefix="perf_";
                }else if(profile.contains("dev")){
                    prefix="dev_";
                }
            }
        }
        if(!StringUtils.isNullOrEmpty(prefix)){
            return
DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix(prefix);
        }
        return DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix("");
    }
}
```

**Comment by derjust** [comment]
Can you please update this Annotation:

```java
@EnableDynamoDBRepositories(
    dynamoDBMapperConfigRef = "dynamoDBMapperConfig",  // This literal has to match the bean name as per the @Bean method - otherwise the default DynamoDBMapperConfig will be used
    basePackages = "com.platform.integration.dynamodb.repository")
```

**Comment by derjust** [comment]
Hi @ravichauhan03,

did this change helped you to use runtime-based table prefixes?

**Comment by ravichauhan03** [comment]
Yes Sebastian, that helped. Thanks for following up.

--
Regards,
Ravi Chauhan
+91-9958597300
Skype: ravichauhan03 <ravichauhan03@gmail.com>
